[package]
name = "rust-chip8"
version = "1.0.0"
edition = "2021"
authors = ["Geoffrey Ballard <geoffreyballard@gmail.com>"]

[dependencies]
dotenv = "0.15.0"
egui = "0.27.2"
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
sdl2 = { version = "^0.35", features = ["ttf"] }
